name: .NET version sweeper

defaults:
  run:
    # bash --noprofile --norc -e(o) pipefail {0}
    shell: bash

on:
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:
    inputs:
      reason:
        description: The reason for running the workflow
        required: true
        default: Manual run
      support:
        description: The support level to target (STS, LTS, or Preview).
        required: true
        default: LTS

concurrency:
  # github.event.pull_request.number || github.ref: pull request number or branch name if not a pull request
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CHECK_PERMISSIONS: 0

permissions: {}

jobs:
  version-sweep:
    name: Sweep .NET Versions
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      issues: write # Need to create issue
      contents: write # Need to commit changes
      pull-requests: write # Need to create PR
    steps:
      - id: check-permissions
        name: Check action permissions
        uses: GitHubSecurityLab/actions-permissions/monitor@b25f731bf2f9eb9748c2e9757d366c3e72fa2109 # v1.0.2-beta8
        if: env.CHECK_PERMISSIONS == '1'
      - id: checkout-repo
        name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true # Need to push changes
      - id: print-reason
        name: Print manual run reason
        env:
          REASON: ${{ github.event.inputs.reason }}
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Reason: $REASON"
      # Issues will be automatically created for any non-ignored projects that are targeting non-LTS versions
      - id: dotnet-version-sweeper
        name: .NET version sweeper
        uses: dotnet/versionsweeper@4db106fb89f4c6191a1e3901f953b1aae05331b5 # v4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          owner: ${{ github.repository_owner }}
          name: ${{ github.repository }}
          branch: ${{ github.ref }}
          sdkCompliance: true
      - id: create-prs
        name: Create pull requests
        if: steps.dotnet-version-sweeper.outputs.has-remaining-work == 'true'
        env:
          UPGRADE_PROJECTS: ${{ steps.dotnet-version-sweeper.outputs.upgrade-projects }}
          SUPPORT: ${{ inputs.support }}
          DOTNET_CLI_TELEMETRY_OPTOUT: true
        run: |
          upgradeProjects="$UPGRADE_PROJECTS"

          # Install .NET Upgrade Assistant global tool
          dotnet tool install --global upgrade-assistant

          # Iterate all upgrade projects
          for projectDir in "${upgradeProjects[@]}"; do
            echo "Project Directory: $projectDir"

            # Create a new branch
            git checkout -b upgrade/$projectDir

            # Perform the upgrade using upgrade-assistant
            upgrade-assistant upgrade "$projectDir" --non-interactive -t "$SUPPORT"

            # Commit the changes
            git add .
            git commit -m ".NET Version Sweeper: Upgraded $projectDir"

            # Push the branch to the repository
            git push origin upgrade/$projectDir

            # Create a pull request
            gh pr create \
              --base main \
              --head upgrade/$projectDir \
              --title "Upgraded $projectDir" \
              --body "Proposed upgrade for $projectDir"
          done
